GET http://localhost:3000/api/members

###

POST http://localhost:3000/api/members
Content-Type: application/json

  {
    "id": 11,
    "name": "Zake",
    "team": "engineering",
    "position": "Android Developer",
    "emailAddress": "Zake@google.com",
    "phoneNumber": "010-xxxx-xxxx",
    "admissionDate": "2021/12/10",
    "birthday": "1995/09/08",
    "profileImage": "profile11.png"
  }